      - name: Executar Agente Financeiro
        env:
          # Aqui o GitHub pega o Secret e transforma em Vari√°vel de Ambiente
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python script.py
